project:
  type: website

website:
  title: "MY LIFE"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/JoThePOkeMOn
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cyborg
    css: styles.css



